#!/usr/bin/env python3
"""Compute official-style BERTScore values for UniMoral RQ4 artifacts.

This script is intentionally separate from the default release builder because
BERTScore downloads multilingual encoder weights and can be slow. It consumes
the tracked `unimoral-sample-predictions.csv` export and writes a compact
per-sample file that `build_unimoral_artifacts.py` merges when present.
"""

from __future__ import annotations

import argparse
import csv
import json
import sys
from collections import defaultdict
from pathlib import Path
from typing import Callable

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_RELEASE_DIR = ROOT / "results" / "release" / "2026-04-19-option1"

BS_LANG = {
    "English": "en",
    "Spanish": "es",
    "Arabic": "ar",
    "Russian": "ru",
    "Chinese": "zh",
    "Hindi": "hi",
}


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open(newline="", encoding="utf-8") as handle:
        return list(csv.DictReader(handle))


def write_csv(path: Path, rows: list[dict[str, object]], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, lineterminator="\n")
        writer.writeheader()
        writer.writerows(rows)


def _target_list(row: dict[str, str]) -> list[str]:
    try:
        parsed = json.loads(row.get("target_json") or "[]")
    except json.JSONDecodeError:
        return []
    if not isinstance(parsed, list):
        return []
    return [str(item) for item in parsed if str(item).strip()]


def rq4_rows(rows: list[dict[str, str]], *, model_filter: set[str] | None = None) -> list[dict[str, str]]:
    output = []
    for row in rows:
        if row.get("task_name") != "unimoral_consequence_generation":
            continue
        if model_filter is not None and row.get("line_label") not in model_filter:
            continue
        if not _target_list(row):
            continue
        output.append(row)
    return output


def compute_rows(
    rows: list[dict[str, str]],
    *,
    score_fn: Callable[..., tuple[object, object, object]],
    batch_size: int,
    device: str | None = None,
) -> list[dict[str, object]]:
    by_language: dict[str, list[dict[str, str]]] = defaultdict(list)
    for row in rows:
        by_language[row.get("language") or "English"].append(row)

    output = []
    for language, language_rows in sorted(by_language.items()):
        bs_lang = BS_LANG.get(language, "en")
        pair_predictions = []
        pair_references = []
        pair_keys = []
        for row in language_rows:
            if not row.get("prediction", "").strip():
                output.append(
                    {
                        "line_label": row["line_label"],
                        "task_name": row["task_name"],
                        "sample_id": row["sample_id"],
                        "language": language,
                        "bert_score_f1": 0.0,
                    }
                )
                continue
            for reference in _target_list(row):
                pair_predictions.append(row["prediction"])
                pair_references.append(reference)
                pair_keys.append((row["line_label"], row["task_name"], row["sample_id"]))

        per_sample: dict[tuple[str, str, str], float] = {}
        if pair_predictions:
            kwargs = {"lang": bs_lang, "verbose": False, "batch_size": batch_size}
            if device:
                kwargs["device"] = device
            _, _, f1 = score_fn(pair_predictions, pair_references, **kwargs)
            scores = f1.tolist() if hasattr(f1, "tolist") else list(f1)
            for key, value in zip(pair_keys, scores):
                per_sample[key] = max(per_sample.get(key, 0.0), float(value))

        for row in language_rows:
            key = (row["line_label"], row["task_name"], row["sample_id"])
            if key not in per_sample:
                continue
            output.append(
                {
                    "line_label": row["line_label"],
                    "task_name": row["task_name"],
                    "sample_id": row["sample_id"],
                    "language": language,
                    "bert_score_f1": round(per_sample[key], 8),
                }
            )
    return output


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--input",
        default=DEFAULT_RELEASE_DIR / "unimoral-sample-predictions.csv",
        type=Path,
        help="Sample prediction CSV generated by scripts/build_unimoral_artifacts.py.",
    )
    parser.add_argument(
        "--output",
        default=DEFAULT_RELEASE_DIR / "unimoral-rq4-bertscore.csv",
        type=Path,
        help="Per-sample BERTScore CSV to merge back into release artifacts.",
    )
    parser.add_argument("--batch-size", default=64, type=int)
    parser.add_argument("--device", default=None, help="Optional torch device passed to bert_score.score, e.g. cpu or cuda:0.")
    parser.add_argument(
        "--model-filter",
        default="",
        help="Optional comma-separated model-line labels to score, useful for resuming partial files.",
    )
    args = parser.parse_args()

    try:
        from bert_score import score
    except ImportError:
        print(
            "Missing optional dependency 'bert_score'. Install it in the active environment "
            "before running this offline metric script.",
            file=sys.stderr,
        )
        return 2

    model_filter = {item.strip() for item in args.model_filter.split(",") if item.strip()} or None
    rows = rq4_rows(read_csv(args.input), model_filter=model_filter)
    output = compute_rows(rows, score_fn=score, batch_size=args.batch_size, device=args.device)
    write_csv(args.output, output, ["line_label", "task_name", "sample_id", "language", "bert_score_f1"])
    print(f"Wrote {len(output)} UniMoral RQ4 BERTScore rows to {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
